version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./dataset.data:/app/dataset.data 
      - ./database.db:/app/database.db
    environment:
      - FLASK_ENV=development
    networks:
      - flask-network


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-app
    networks:
      - flask-network

networks:
  flask-network: